[envs.default]
dependencies = ["perturbo[test]"]

[envs.default.scripts]
test = "pytest {args:tests}"

[envs.perturbo-dev]
dependencies = [
    "perturbo[test]",
    # For notebooks
    "pytest",
    "ipykernel",
    "ipython",
    "seaborn",
    "scanpy",
    "matplotlib",
    "graphviz",
]

[[envs.all.matrix]]
python = ["3.8", "3.10"]
